# -*- coding: utf-8 -*-
"""meow_songs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CH78lummeM9KSfphMfpkgGKHrfP8J_Uh
"""

# !pip install spleeter

# !spleeter separate  -p spleeter:2stems -o "/content/drive/MyDrive/" -c wav  "/content/drive/MyDrive/sonh_1.mp3"

# !pip install pydub

from pydub import AudioSegment

# Load the instrumental (accompaniment) and new meow vocals
instrumental = AudioSegment.from_file("/content/drive/MyDrive/song/accompaniment.wav")
new_vocals = AudioSegment.from_file("/content/drive/MyDrive/song/meow_vocals_output.wav")

# Adjust volumes to balance the mix
instrumental = instrumental - 3  # Reduce instrumental volume by 3dB
new_vocals = new_vocals  # Increase vocal volume by 2dB

# Apply fade in/out manually to vocals for smooth transitions (crossfade simulation)
new_vocals = new_vocals.fade_in(1000).fade_out(1000)  # 1 second fade-in and fade-out

# Overlay the vocals on top of the instrumental
final_song = instrumental.overlay(new_vocals)

# Save the final song
final_song.export("/content/drive/MyDrive/song/final_song.wav", format="wav")

# from pydub import AudioSegment

# # Load the instrumental (accompaniment) and new meow vocals
# instrumental = AudioSegment.from_file("/content/drive/MyDrive/song_cut/accompaniment.wav")
# new_vocals = AudioSegment.from_file("/content/drive/MyDrive/meow_vocals.wav")

# # Adjust volumes to balance the mix
# instrumental = instrumental - 3  # Reduce instrumental volume by 3dB
# new_vocals = new_vocals + 2  # Increase vocal volume by 2dB

# # Apply fade in/out manually to vocals for smooth transitions (crossfade simulation)
# new_vocals = new_vocals.fade_in(1000).fade_out(1000)  # 1 second fade-in and fade-out

# # Overlay the vocals on top of the instrumental
# final_song = instrumental.overlay(new_vocals)

# # Slow down the final song by reducing the frame rate
# def slow_down(sound, speed_factor=0.8):
#     slowed_down_sound = sound._spawn(sound.raw_data, overrides={
#          "frame_rate": int(sound.frame_rate * speed_factor)
#     }).set_frame_rate(sound.frame_rate)
#     return slowed_down_sound

# # Apply slow down (e.g., 80% of original speed)
# slower_song = slow_down(final_song, speed_factor=0.8)

# # Save the slowed-down final song
# slower_song.export("/content/drive/MyDrive/song_cut/final_song_slowed.wav", format="wav")


# from pydub import AudioSegment

# # Load the instrumental (accompaniment) and new meow vocals
# instrumental = AudioSegment.from_file("/content/drive/MyDrive/billi/accompaniment.wav")
# new_vocals = AudioSegment.from_file("/content/drive/MyDrive/billi_meow_mod.wav")

# # Superimpose the meow vocals over the instrumental
# final_song = instrumental.overlay(new_vocals2)

# # Save the final song
# final_song.export("/content/drive/MyDrive/song/final_song.wav", format="wav")
