# Changes here will be overwritten by Copier
_commit: 1.2.6
_src_path: https://github.com/pawamoy/copier-pdm.git
author_email: vandy.goel23@gmail.com
author_fullname: vandyG
author_username: vandyG
copyright_date: '2024'
copyright_holder: vandyG
copyright_holder_email: vandy.goel23@gmail.com
copyright_license: MIT License
insiders: false
project_description: Finally, a cat-astrophic rendition of your favorite songs!
project_name: meoww
python_package_command_line_name: meoww
python_package_distribution_name: meoww
python_package_import_name: meoww
repository_name: meoww
repository_namespace: vandyG
repository_provider: github.com

